heat_template_version: 2018-08-31

parameters:
  key-pair-name:
    type: string
    description: The name of the key pair.
  key-pair-pubkey:
    type: string
    description: The optional public key

resources:
  key-pair:
    type: OS::Nova::KeyPair
    properties:
      name: { get_param: key-pair-name }
      public_key: { get_param: key-pair-pubkey }