heat_template_version: 2018-08-31

parameters:
  key-pair-name:
    type: string
    description: The name of the key pair.
  key-pair-pubkey:
    type: string
    description: The optional public key
  private-network:
    type: string
    description: Name of the Private Network
  private-network-subnet:
    type: string
    description: Name of the Private Network Subnet
  cidr-ip:
    type: string
    description: Private Network IP Range
  private-network-gateway-ip:
    type: string
    description: Gateway IP of Private Network

resources:
  key-pair:
    type: OS::Nova::KeyPair
    properties:
      name: { get_param: key-pair-name }
      public_key: { get_param: key-pair-pubkey }

  auth-app:
    type: OS::Neutron::Net
    properties:
      name: { get_param: private-network }

  auth-app-sub:
    type: OS::Neutron::Subnet
    properties:
      network: { get_resource: auth-app }
      name: { get_param: private-network-subnet }
      cidr: { get_param: cidr-ip }
      gateway_ip: { get_param: private-network-gateway-ip }
      dns_nameservers: 
        - 8.8.8.8
      enable_dhcp: true