heat_template_version: 2018-08-31

parameters:
  loadbalancer-name:
    type: string
    description: Name of this Load Balancer
  loadbalancer-subnet:
    type: string
    description: The name or ID of the subnet on which to allocate the VIP address
  loadbalancerlistener-protocol:
    type: string
    description: Protocol on which to listen for the client traffic
  loadbalancerlistener-protocol-port:
    type: string
    description: Protocol Port
  lb-algorithm: 
    type: string
    description: The algorithm used to distribute load between the members of the pool
  lb-pool-protocol:
    type: string
    description: Protocol of the pool

resources:
  LoadBalancer:
    type: OS::Octavia::LoadBalancer
    properties:
      name: { get_param: loadbalancer-name }
      vip_subnet: { get_param: loadbalancer-subnet }

  LoadBalancerListener:
    type: OS::Octavia::Listener
    properties:
      protocol: { get_param: loadbalancerlistener-protocol }
      protocol_port: { get_param: loadbalancerlistener-protocol-port }
      loadbalancer: { get_resource: LoadBalancer }

  LoadBalancerPool:
    type: OS::Octavia::Pool
    properties:
      lb_algorithm: { get_param: lb-algorithm }
      protocol: { get_param: lb-pool-protocol }
      loadbalancer: { get_resource: LoadBalancer }
      listener: { get_resource: LoadBalancerListener }
